exports.seed = async function (knex) {
  await knex("visit").del();
  await knex("visit").insert([
    {
      id: 1,
      coffeeshop_id: 1,
      user_id: 1,
      visited: true,
      on_wishlist: false,
      rating: 4,
      review: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
    },
    {
      id: 2,
      coffeeshop_id: 2,
      user_id: 1,
      visited: true,
      on_wishlist: false,
    },
    {
      id: 3,
      coffeeshop_id: 3,
      user_id: 1,
      visited: false,
      on_wishlist: true,
    },
    {
      id: 4,
      coffeeshop_id: 4,
      user_id: 1,
      visited: true,
      on_wishlist: false,
      rating: 5,
      review: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    },
    {
      id: 5,
      coffeeshop_id: 5,
      user_id: 1,
      visited: true,
      on_wishlist: false,
      rating: 3,
    },
    {
      id: 6,
      coffeeshop_id: 1,
      user_id: 2,
      visited: false,
      on_wishlist: false,
    },
    {
      id: 7,
      coffeeshop_id: 2,
      user_id: 2,
      visited: true,
      rating: 3,
      review:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut, accusamus ratione corporis amet architecto dolorum possimus voluptatem quos, iure beatae quisquam obcaecati dolor mollitia debitis numquam eligendi earum repudiandae excepturi.",
    },
    {
      id: 8,
      coffeeshop_id: 3,
      user_id: 2,
      visited: true,
      on_wishlist: false,
      rating: 5,
    },
    {
      id: 9,
      coffeeshop_id: 4,
      user_id: 2,
      visited: false,
      on_wishlist: true,
    },
    {
      id: 10,
      coffeeshop_id: 5,
      user_id: 2,
      visited: false,
      on_wishlist: true,
    },
    {
      id: 11,
      coffeeshop_id: 1,
      user_id: 3,
      visited: true,
      on_wishlist: false,
      rating: 4,
    },
    {
      id: 12,
      coffeeshop_id: 2,
      user_id: 3,
      visited: false,
      on_wishlist: true,
    },
    {
      id: 13,
      coffeeshop_id: 3,
      user_id: 3,
      visited: true,
      review:
        "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Facilis ratione hic veniam cum possimus, voluptatem quidem adipisci pariatur voluptatibus ad repellendus nam consequuntur animi aspernatur vitae totam neque debitis porro?",
    },
    {
      id: 14,
      coffeeshop_id: 4,
      user_id: 3,
      visited: false,
      on_wishlist: false,
    },
    {
      id: 15,
      coffeeshop_id: 5,
      user_id: 3,
      visited: false,
      on_wishlist: true,
    },
    {
      id: 16,
      coffeeshop_id: 1,
      user_id: 4,
      visited: true,
      rating: 5,
      review:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis reiciendis necessitatibus hic quaerat velit, iusto dolore recusandae corrupti et, quod repellendus quasi voluptatibus ex incidunt ab itaque fugiat reprehenderit magnam.",
    },
    {
      id: 17,
      coffeeshop_id: 2,
      user_id: 4,
      visited: false,
      on_wishlist: true,
    },
    {
      id: 18,
      coffeeshop_id: 3,
      user_id: 4,
      visited: false,
      on_wishlist: true,
    },
    {
      id: 19,
      coffeeshop_id: 4,
      user_id: 4,
      visited: false,
      on_wishlist: false,
    },
    {
      id: 20,
      coffeeshop_id: 5,
      user_id: 4,
      visited: true,
    },

    {
      id: 21,
      coffeeshop_id: 1,
      user_id: 5,
      on_wishlist: true,
    },
    {
      id: 22,
      coffeeshop_id: 2,
      user_id: 5,
      visited: false,
      on_wishlist: false,
    },
    {
      id: 23,
      coffeeshop_id: 3,
      user_id: 5,
      visited: true,
      rating: 5,
    },
    {
      id: 24,
      coffeeshop_id: 4,
      user_id: 5,
      visited: false,
      on_wishlist: true,
    },
    {
      id: 25,
      coffeeshop_id: 5,
      user_id: 5,
      visited: true,
      rating: 4,
      review:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam facilis doloribus magni, itaque modi molestiae eum magnam non, ut voluptates quam consequuntur ab, ad odio. Minima sed eaque harum mollitia.",
    },
  ]);
};
